version: '3.3'
services:
  vendors-api:
    image: jhawk7/vendors-api
    build: .
    ports:
      - '3000:3000'
    restart: on-failure
    env_file:
      - ./.env.test

  vendors-db:
    image: jhawk7/vendors-db
    restart: on-failure
    env_file:
      - ./.env.test
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql